/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Forms.panelPrincipal;

import Controller.RolesController;
import Controller.UsuarioController;
import DTOs.UsuariosDTO;
import Helpers.MensajesJOP_Errores;
import Helpers.ValidarPassword;
import Models.Roles;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Deyson Vente
 */
public class frmNuevoUsuario extends javax.swing.JInternalFrame {
    ValidarPassword validarPassword = ValidarPassword.getInstanciaValidarPassword();
    
    /**
     * Creates new form frmNuevoUsuario
     */
    public frmNuevoUsuario() {
        initComponents();

        RolesController rolControl = new RolesController();
        List<Roles> listaRoles = rolControl.obtenerRoles();
        for (Roles rol : listaRoles) {
            cbRoles.addItem(rol.getNombreRol());
            System.out.println("Rol: " + rol.getNombreRol());
        }

    }

    public void limpiarCampos() {
        txtNombre.setText("");
        txtNombreUsuario.setText("");
        txtApellido.setText("");
        txtClave.setText("");
        txtConfirmacion.setText("");
        cbRoles.setSelectedIndex(0);
        txtNombre.requestFocus();
        txtBuscar_Id.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosUsuario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        cbRoles = new javax.swing.JComboBox();
        lblClaveUsuario = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        lblConfrClaveUsuario = new javax.swing.JLabel();
        txtConfirmacion = new javax.swing.JPasswordField();
        lbl_IdBucar = new javax.swing.JLabel();
        txtBuscar_Id = new javax.swing.JTextField();
        panelTop = new javax.swing.JPanel();
        lblInformacion = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlInferior = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios_1.png"))); // NOI18N

        panelDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos para el Usuario"));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApellido.setText("Apellido");

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreUsuario.setText("Nombre usuario");

        txtNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreUsuarioFocusGained(evt);
            }
        });

        lblRol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRol.setText("Rol del Usuario:");

        lblClaveUsuario.setBackground(new java.awt.Color(204, 204, 204));
        lblClaveUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClaveUsuario.setText("Contraseña:");

        lblConfrClaveUsuario.setBackground(new java.awt.Color(204, 204, 204));
        lblConfrClaveUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfrClaveUsuario.setText("Confirmar contraseña:");

        lbl_IdBucar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_IdBucar.setText("Buscar Id:");

        javax.swing.GroupLayout panelDatosUsuarioLayout = new javax.swing.GroupLayout(panelDatosUsuario);
        panelDatosUsuario.setLayout(panelDatosUsuarioLayout);
        panelDatosUsuarioLayout.setHorizontalGroup(
                panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDatosUsuarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelDatosUsuarioLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRol)
                                        .addComponent(lblNombre)
                                        .addComponent(lblClaveUsuario)
                                        .addComponent(lbl_IdBucar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDatosUsuarioLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelDatosUsuarioLayout.createSequentialGroup()
                                                .addGroup(panelDatosUsuarioLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtNombre,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbRoles,
                                                                javax.swing.GroupLayout.Alignment.LEADING, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtClave,
                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelDatosUsuarioLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblConfrClaveUsuario)
                                                        .addComponent(lblApellido)
                                                        .addComponent(lblNombreUsuario))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelDatosUsuarioLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtConfirmacion)
                                                        .addComponent(txtApellido)
                                                        .addComponent(txtNombreUsuario)))
                                        .addGroup(panelDatosUsuarioLayout.createSequentialGroup()
                                                .addComponent(txtBuscar_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        panelDatosUsuarioLayout.setVerticalGroup(
                panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDatosUsuarioLayout.createSequentialGroup()
                                .addGroup(panelDatosUsuarioLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNombre)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblApellido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDatosUsuarioLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombreUsuario)
                                        .addComponent(lblRol)
                                        .addComponent(cbRoles, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDatosUsuarioLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblClaveUsuario)
                                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblConfrClaveUsuario)
                                        .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosUsuarioLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_IdBucar)
                                        .addComponent(txtBuscar_Id, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(51, Short.MAX_VALUE)));

        lblInformacion.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        lblInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacion.setText("Ingresa la información del nuevo usuario");
        lblInformacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoEmpresa.png"))); // NOI18N

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
                panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(312, 312, 312))
                        .addGroup(panelTopLayout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(lblInformacion, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(218, 218, 218)));
        panelTopLayout.setVerticalGroup(
                panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTopLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblInformacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        pnlInferior.setBackground(new java.awt.Color(0, 204, 204));

        btnConsultar.setBackground(new java.awt.Color(255, 255, 204));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 153));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(153, 255, 255));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 0, 0));
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
                pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInferiorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(223, 223, 223)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(73, 73, 73)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        pnlInferiorLayout.setVerticalGroup(
                pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlInferiorLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnConsultar)
                                        .addComponent(btnLimpiar)
                                        .addComponent(btnNuevo)
                                        .addComponent(btnActualizar)
                                        .addComponent(btnEliminar1))
                                .addContainerGap()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(37, Short.MAX_VALUE)
                                .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE)));

        panelDatosUsuario.getAccessibleContext().setAccessibleName(getName());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultarActionPerformed

        String idUsuario = txtBuscar_Id.getText();

        if (idUsuario.equals("")) {
            JOptionPane.showMessageDialog(null, MensajesJOP_Errores.CampoIdVacio());
            return;
        }

        UsuarioController controller = new UsuarioController();
        UsuariosDTO traerDatos = controller.lectura(Integer.parseInt(idUsuario));

        if (traerDatos != null) {
            txtNombre.setText(traerDatos.getNombre());
            txtApellido.setText(traerDatos.getApellido());
            txtNombreUsuario.setText(traerDatos.getNombreUsuario());

            switch (traerDatos.getRol_Id()) {
                case 1:
                    // Admin
                    cbRoles.setSelectedIndex(0);
                    break;
                case 2:
                    // Propietario
                    cbRoles.setSelectedIndex(1);
                    break;
                default:
                    // Empleado
                    cbRoles.setSelectedIndex(2);
                    break;
            }
        }

    }// GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarActionPerformed

        limpiarCampos();
    }// GEN-LAST:event_btnLimpiarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuevoActionPerformed

        UsuariosDTO nuevoUsuario = new UsuariosDTO();
        String nombre, apellido, usuarioN, clave, confirmacion;
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        usuarioN = txtNombreUsuario.getText();
        int rol;
        clave = new String(txtClave.getPassword());
        confirmacion = new String(txtConfirmacion.getPassword());

        if (nombre.isEmpty() || apellido.isEmpty() || usuarioN.isEmpty() || clave.isEmpty() || confirmacion.isEmpty()) {
            JOptionPane.showMessageDialog(null,MensajesJOP_Errores.CamposSinLlenar());
        } else if (!clave.equals(confirmacion)) {
            JOptionPane.showMessageDialog(null, MensajesJOP_Errores.PasswordNoCoincide());
        } else {

            if (clave.length() < 10 && confirmacion.length() < 10) {
                JOptionPane.showMessageDialog(rootPane, MensajesJOP_Errores.PasswordCorto());
                txtClave.requestFocus();
                return;
            } else {
                if (validarPassword.Comprueba(clave)) {
                    // Los campos de entrada son válidos
                    // Continúa con el procesamiento de los datos
                    switch (cbRoles.getSelectedIndex()) {
                        case 0:
                            // Admin
                            rol = 1;
                            break;
                        case 1:
                            // Propietario
                            rol = 2;
                            break;
                        default:
                            // Empleado
                            rol = 3;
                            break;
                    }
                    nuevoUsuario.setNombre(nombre);
                    nuevoUsuario.setApellido(apellido);
                    nuevoUsuario.setClave(clave);
                    nuevoUsuario.setNombreUsuario(usuarioN);
                    nuevoUsuario.setRol_Id(rol);

                    nuevoUsuario.encriptaPassword(nuevoUsuario);
                    limpiarCampos();
                    return;
                }
                JOptionPane.showMessageDialog(null,
                        MensajesJOP_Errores.PasswordInseguro(),
                        "Contraseña Insegura", HEIGHT);
            }

        }

    }// GEN-LAST:event_btnNuevoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActualizarActionPerformed

        UsuariosDTO actualizarUsuario = new UsuariosDTO();
        String nombre, apellido, usuarioN, clave, confirmacion;
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        usuarioN = txtNombreUsuario.getText();
        int rol;
        clave = new String(txtClave.getPassword());
        confirmacion = new String(txtConfirmacion.getPassword());

        if (nombre.isEmpty() || apellido.isEmpty() || usuarioN.isEmpty() || clave.isEmpty() || confirmacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, MensajesJOP_Errores.CamposSinLlenar());
        } else if (!clave.equals(confirmacion)) {
            JOptionPane.showMessageDialog(null, MensajesJOP_Errores.PasswordNoCoincide());
        } else {
            if (validarPassword.Comprueba(clave)) {
                // Los campos de entrada son válidos
                // Continúa con el procesamiento de los datos
                rol = switch (cbRoles.getSelectedIndex()) {
                    case 0 -> 1;
                    case 1 -> 2;
                    default -> 3;
                }; // Admin
                   // Propietario
                   // Empleado
                actualizarUsuario.setNombre(nombre);
                actualizarUsuario.setApellido(apellido);
                actualizarUsuario.setClave(clave);
                actualizarUsuario.setNombreUsuario(usuarioN);
                actualizarUsuario.setRol_Id(rol);
                int idUsuario = Integer.parseInt(txtBuscar_Id.getText());

                actualizarUsuario.update(actualizarUsuario, idUsuario);
                limpiarCampos();
                return;
            }
            JOptionPane.showMessageDialog(null,
                    MensajesJOP_Errores.PasswordInseguro(),
                    "Contraseña Insegura", HEIGHT);

        }

    }// GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminar1ActionPerformed

        String idUsuario = txtBuscar_Id.getText();

        if (idUsuario.equals("")) {
            JOptionPane.showMessageDialog(null, MensajesJOP_Errores.CampoIdVacio());

        }
        UsuarioController controller = new UsuarioController();
        controller.eliminacion(Integer.parseInt(idUsuario));
        limpiarCampos();
    }// GEN-LAST:event_btnEliminar1ActionPerformed

    private void txtNombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtNombreUsuarioFocusGained
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        // Generar un numero aleatorio
        int randomNum = (int) (Math.random() * 101 + (480 / 5));

        // Obtiene la primera palabra del nombre y el apellido para crear el nombre de
        // usuario
        String nombreUsuario = nombre.split(" ")[0].toLowerCase() + "_" + apellido.split(" ")[0].toLowerCase()
                + randomNum;
        txtNombreUsuario.setText(nombreUsuario);
    }// GEN-LAST:event_txtNombreUsuarioFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cbRoles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblClaveUsuario;
    private javax.swing.JLabel lblConfrClaveUsuario;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lbl_IdBucar;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JPanel panelDatosUsuario;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar_Id;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JPasswordField txtConfirmacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
