package Forms;

import Forms.panelPrincipal.Ayuda.frmAcercaDe;
import Forms.panelPrincipal.Reportes.frmHistorial;
import Forms.panelPrincipal.Reportes.frmUsuarios;
import Forms.panelPrincipal.frmNuevoPropietario;
import Forms.panelPrincipal.frmNuevoUsuario;
import Forms.panelPrincipal.frmNuevoVehiculo;
import java.awt.event.ActionEvent;
import java.time.LocalDate;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;


public class frmPrincipal extends javax.swing.JFrame {

    LocalDate objeto_fecha_actual = LocalDate.now();
    

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();

        actualizarHora();
        // Crear un Timer que llame a la función actualizarHora cada 1 segundo
        Timer timer = new Timer(1000, (ActionEvent e) -> {
            actualizarHora();
        });
        timer.start();

        lblFechaActual.setText(objeto_fecha_actual.toString());

        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnEscritorio = new javax.swing.JDesktopPane();
        panelMostrandoFecha = new javax.swing.JPanel();
        lblTituloFechaActual = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        lblMostrarHora = new javax.swing.JLabel();
        lblParaImagenIzquierda = new javax.swing.JLabel();
        lblParaImagenDerecha = new javax.swing.JLabel();
        lblImagenIzquierda = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNuevo = new javax.swing.JMenu();
        mnuNuevo_Usuario = new javax.swing.JMenuItem();
        mnuNuevo_Vehiculo = new javax.swing.JMenuItem();
        mnuNuevo_Propietario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuNuevo_Salir = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuReportes_Historial = new javax.swing.JMenuItem();
        mnuReportes_Usuarios = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAyuda_AcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración Mr. Kurt");

        dpnEscritorio.setBackground(new java.awt.Color(242, 242, 242));
        dpnEscritorio.setMaximumSize(new java.awt.Dimension(1820, 780));
        dpnEscritorio.setPreferredSize(new java.awt.Dimension(956, 468));

        panelMostrandoFecha.setBackground(new java.awt.Color(0, 153, 153));
        panelMostrandoFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 0, 0)));
        panelMostrandoFecha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblTituloFechaActual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloFechaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloFechaActual.setText("Fecha Actual del Sistema");

        lblFechaActual.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblFechaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaActual.setText("muestraFecha");

        javax.swing.GroupLayout panelMostrandoFechaLayout = new javax.swing.GroupLayout(panelMostrandoFecha);
        panelMostrandoFecha.setLayout(panelMostrandoFechaLayout);
        panelMostrandoFechaLayout.setHorizontalGroup(
            panelMostrandoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrandoFechaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelMostrandoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrandoFechaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        panelMostrandoFechaLayout.setVerticalGroup(
            panelMostrandoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrandoFechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloFechaActual)
                .addGap(18, 18, 18)
                .addComponent(lblFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        lblMostrarHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMostrarHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrarHora.setText("muestraHoraActual");
        lblMostrarHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 153, 0)));

        lblParaImagenIzquierda.setBackground(new java.awt.Color(242, 242, 242));
        lblParaImagenIzquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParaImagenIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoEmpresaCircular225.png"))); // NOI18N

        lblParaImagenDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seguro_de_auto.png"))); // NOI18N

        lblImagenIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N

        dpnEscritorio.setLayer(panelMostrandoFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(lblMostrarHora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(lblParaImagenIzquierda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(lblParaImagenDerecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(lblImagenIzquierda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnEscritorioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblImagenIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 246, Short.MAX_VALUE)
                .addGroup(dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpnEscritorioLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblMostrarHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addGroup(dpnEscritorioLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblParaImagenIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnEscritorioLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(panelMostrandoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43)))
                .addComponent(lblParaImagenDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 246, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpnEscritorioLayout.createSequentialGroup()
                        .addComponent(panelMostrandoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 33, Short.MAX_VALUE)
                        .addComponent(lblParaImagenIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblMostrarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(lblImagenIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblParaImagenDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuNuevo.setText("Nuevo");

        mnuNuevo_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios_16.png"))); // NOI18N
        mnuNuevo_Usuario.setText("Ingresar Nuevo Usuarios");
        mnuNuevo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo_UsuarioActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo_Usuario);

        mnuNuevo_Vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche_16.png"))); // NOI18N
        mnuNuevo_Vehiculo.setText("Ingresar Nueveo Vehiculo");
        mnuNuevo_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo_VehiculoActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo_Vehiculo);

        mnuNuevo_Propietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/propietario_16.png"))); // NOI18N
        mnuNuevo_Propietario.setText("Ingresar Nuevo Propietario");
        mnuNuevo_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo_PropietarioActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo_Propietario);
        mnuNuevo.add(jSeparator1);

        mnuNuevo_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_sesion.png"))); // NOI18N
        mnuNuevo_Salir.setText("Salir");
        mnuNuevo_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo_SalirActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo_Salir);

        jMenuBar1.add(mnuNuevo);

        mnuReportes.setText("Reportes");

        mnuReportes_Historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial.png"))); // NOI18N
        mnuReportes_Historial.setText("Historial Vehiculos");
        mnuReportes_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportes_HistorialActionPerformed(evt);
            }
        });
        mnuReportes.add(mnuReportes_Historial);

        mnuReportes_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios_1.png"))); // NOI18N
        mnuReportes_Usuarios.setText("Usuarios Registrados");
        mnuReportes_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportes_UsuariosActionPerformed(evt);
            }
        });
        mnuReportes.add(mnuReportes_Usuarios);

        jMenuBar1.add(mnuReportes);

        mnuAyuda.setText("Ayuda");

        mnuAyuda_AcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acerca_de.png"))); // NOI18N
        mnuAyuda_AcercaDe.setText("Acerca de");
        mnuAyuda_AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyuda_AcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAyuda_AcercaDe);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNuevo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo_UsuarioActionPerformed
        // TODO add your handling code here:
        frmNuevoUsuario nUsuario = new frmNuevoUsuario();
        dpnEscritorio.add(nUsuario);
        nUsuario.setVisible(true);
    }//GEN-LAST:event_mnuNuevo_UsuarioActionPerformed

    private void mnuNuevo_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo_VehiculoActionPerformed
        // TODO add your handling code here:
        frmNuevoVehiculo nVehiculo = new frmNuevoVehiculo();
        dpnEscritorio.add(nVehiculo);
        nVehiculo.setVisible(true);
    }//GEN-LAST:event_mnuNuevo_VehiculoActionPerformed

    private void mnuNuevo_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo_PropietarioActionPerformed
        // TODO add your handling code here:
        frmNuevoPropietario nPropietario = new frmNuevoPropietario();
        dpnEscritorio.add(nPropietario);
        nPropietario.setVisible(true);
    }//GEN-LAST:event_mnuNuevo_PropietarioActionPerformed

    private void mnuReportes_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportes_HistorialActionPerformed
        // TODO add your handling code here:
        frmHistorial miHistorial = new frmHistorial();
        dpnEscritorio.add(miHistorial);
        miHistorial.setVisible(true);
    }//GEN-LAST:event_mnuReportes_HistorialActionPerformed

    private void mnuReportes_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportes_UsuariosActionPerformed
        // TODO add your handling code here:
        frmUsuarios listaUsuarios = new frmUsuarios();
        dpnEscritorio.add(listaUsuarios);
        listaUsuarios.setVisible(true);
    }//GEN-LAST:event_mnuReportes_UsuariosActionPerformed

    private void mnuAyuda_AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyuda_AcercaDeActionPerformed
        // TODO add your handling code here:
        frmAcercaDe about = new frmAcercaDe();
        about.setVisible(true);
    }//GEN-LAST:event_mnuAyuda_AcercaDeActionPerformed

    private void mnuNuevo_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuNuevo_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmPrincipal().setVisible(true);
        });
    }

    public void actualizarHora() {
        // Obtener la hora actual
        LocalTime horaActual = LocalTime.now();

        // Formatear la hora actual
        DateTimeFormatter horaFormateada = DateTimeFormatter.ofPattern("HH:mm:ss");
        String horaActualFormateada = horaActual.format(horaFormateada);

        // Actualizar el texto del JLabel con la hora actualizada
        lblMostrarHora.setText(horaActualFormateada);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblImagenIzquierda;
    private javax.swing.JLabel lblMostrarHora;
    private javax.swing.JLabel lblParaImagenDerecha;
    private javax.swing.JLabel lblParaImagenIzquierda;
    private javax.swing.JLabel lblTituloFechaActual;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuAyuda_AcercaDe;
    private javax.swing.JMenu mnuNuevo;
    private javax.swing.JMenuItem mnuNuevo_Propietario;
    private javax.swing.JMenuItem mnuNuevo_Salir;
    private javax.swing.JMenuItem mnuNuevo_Usuario;
    private javax.swing.JMenuItem mnuNuevo_Vehiculo;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem mnuReportes_Historial;
    private javax.swing.JMenuItem mnuReportes_Usuarios;
    private javax.swing.JPanel panelMostrandoFecha;
    // End of variables declaration//GEN-END:variables

}
