/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Forms.panelPrincipal.frmNuevoPropietario;
import Forms.panelPrincipal.frmNuevoUsuario;
import Forms.panelPrincipal.frmNuevoVehiculo;


/**
 *
 * @author admin
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNuevo = new javax.swing.JMenu();
        mnuNuevo_Usuario = new javax.swing.JMenuItem();
        mnuNuevo_Vehiculo = new javax.swing.JMenuItem();
        mnuNuevo_Propietario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuNuevo_Salir = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuReportes_Compras = new javax.swing.JMenuItem();
        mnuReportes_Ventas = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAyuda_AcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración Mr. Kurt");

        dpnEscritorio.setBackground(new java.awt.Color(242, 242, 242));
        dpnEscritorio.setMaximumSize(new java.awt.Dimension(1820, 780));
        dpnEscritorio.setPreferredSize(new java.awt.Dimension(956, 468));

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        mnuNuevo.setText("Nuevo");

        mnuNuevo_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios_16.png"))); // NOI18N
        mnuNuevo_Usuario.setText("Usuarios");
        mnuNuevo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo_UsuarioActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo_Usuario);

        mnuNuevo_Vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche_16.png"))); // NOI18N
        mnuNuevo_Vehiculo.setText("Ingresar Vehiculo");
        mnuNuevo_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo_VehiculoActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo_Vehiculo);

        mnuNuevo_Propietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/propietario_16.png"))); // NOI18N
        mnuNuevo_Propietario.setText("Nuevo Propietario");
        mnuNuevo_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo_PropietarioActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo_Propietario);
        mnuNuevo.add(jSeparator1);

        mnuNuevo_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_sesion.png"))); // NOI18N
        mnuNuevo_Salir.setText("Salir");
        mnuNuevo.add(mnuNuevo_Salir);

        jMenuBar1.add(mnuNuevo);

        mnuReportes.setText("Reportes");

        mnuReportes_Compras.setText("Historial");
        mnuReportes.add(mnuReportes_Compras);

        mnuReportes_Ventas.setText("Usuarios");
        mnuReportes.add(mnuReportes_Ventas);

        jMenuBar1.add(mnuReportes);

        mnuAyuda.setText("Ayuda");

        mnuAyuda_AcercaDe.setText("Acerca de");
        mnuAyuda.add(mnuAyuda_AcercaDe);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNuevo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo_UsuarioActionPerformed
        // TODO add your handling code here:
        frmNuevoUsuario nUsuario = new frmNuevoUsuario();
        dpnEscritorio.add(nUsuario);
        nUsuario.setVisible(true);
    }//GEN-LAST:event_mnuNuevo_UsuarioActionPerformed

    private void mnuNuevo_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo_VehiculoActionPerformed
        // TODO add your handling code here:
        frmNuevoVehiculo nVehiculo = new frmNuevoVehiculo();
        dpnEscritorio.add(nVehiculo);
        nVehiculo.setVisible(true);
    }//GEN-LAST:event_mnuNuevo_VehiculoActionPerformed

    private void mnuNuevo_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo_PropietarioActionPerformed
        // TODO add your handling code here:
        frmNuevoPropietario nPropietario = new frmNuevoPropietario();
        dpnEscritorio.add(nPropietario);
        nPropietario.setVisible(true);
    }//GEN-LAST:event_mnuNuevo_PropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuAyuda_AcercaDe;
    private javax.swing.JMenu mnuNuevo;
    private javax.swing.JMenuItem mnuNuevo_Propietario;
    private javax.swing.JMenuItem mnuNuevo_Salir;
    private javax.swing.JMenuItem mnuNuevo_Usuario;
    private javax.swing.JMenuItem mnuNuevo_Vehiculo;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem mnuReportes_Compras;
    private javax.swing.JMenuItem mnuReportes_Ventas;
    // End of variables declaration//GEN-END:variables
}
